name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, macos-10.15, windows-2022, windows-2019, windows-2016]
        version: [10.15, 12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
